openapi: 3.0.0
info:
  title: API Produits
  version: 1.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Laptop Gaming"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-12-31T23:59:59Z"
        price:
          type: number
          format: float
          example: 999.99
      required:
        - name
        - expiration_datetime
        - price
  parameters:
    LimitParam:
      name: limit
      in: query
      description: Nombre maximum d'éléments
      required: false
      schema:
        type: integer
        example: 10
    QueryParam:
      name: q
      in: query
      description: Terme de recherche
      required: false
      schema:
        type: string
        example: "laptop"
paths:
  /products:
    get:
      summary: Recherche des produits
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/QueryParam'
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Exemple avec plusieurs produits
                  value:
                    - name: "Laptop"
                      expiration_datetime: "2026-01-01T00:00:00Z"
                      price: 1200.50
                    - name: "Smartphone"
                      expiration_datetime: "2025-06-15T12:00:00Z"
                      price: 699.99
                emptyList:
                  summary: Exemple avec liste vide
                  value: []