openapi: 3.0.0
info:
  title: API avec Authentification
  version: 1.0.0
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        identifier:
          type: integer
          example: 1001
        customer_name:
          type: string
          example: "Jean Dupont"
        creation_datetime:
          type: string
          format: date-time
          example: "2024-08-25T10:30:00Z"
        total_amount:
          type: number
          format: float
          example: 150.75
      required:
        - identifier
        - customer_name
        - creation_datetime
        - total_amount
  parameters:
    PageParam:
      name: page
      in: query
      description: Numéro de page
      required: false
      schema:
        type: integer
        example: 1
    SizeParam:
      name: size
      in: query
      description: Taille de la page
      required: false
      schema:
        type: integer
        example: 20
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
paths:
  /products:
    get:
      tags:
        - Products
      summary: Liste des produits
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /orders:
    get:
      tags:
        - Orders
      summary: Liste paginée des commandes
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/SizeParam'
      responses:
        '200':
          description: Liste des commandes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Orders
      summary: Crée une commande
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              sampleOrder:
                value:
                  customer_name: "Marie Martin"
                  creation_datetime: "2024-08-25T14:45:00Z"
                  total_amount: 89.99
      responses:
        '201':
          description: Commande créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'