openapi: 3.0.0
info:
  title: API Gestion de Profils Utilisateurs
  version: 1.0.0
components:
  schemas:
    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
          example: "Jean"
        last_name:
          type: string
          example: "Dupont"
        birthdate:
          type: string
          format: date
          example: "1990-05-15"
        email:
          type: string
          format: email
          example: "jean.dupont@email.com"
    Address:
      type: object
      properties:
        address_street:
          type: string
          example: "123 Rue Principale"
        address_city:
          type: string
          example: "Paris"
        address_country:
          type: string
          example: "France"
        address_postal_code:
          type: string
          example: "75001"
    Preferences:
      type: object
      properties:
        needs_newsletter:
          type: boolean
          example: true
        language:
          type: string
          enum: [mg, fr, eng]
          example: "fr"
    CreateUserProfile:
      type: object
      properties:
        personal_info:
          $ref: '#/components/schemas/PersonalInfo'
        address:
          $ref: '#/components/schemas/Address'
        preferences:
          $ref: '#/components/schemas/Preferences'
      required:
        - personal_info
        - address
        - preferences
    UserProfile:
      allOf:
        - $ref: '#/components/schemas/CreateUserProfile'
        - type: object
          properties:
            identifier:
              type: string
              example: "user123"
          required:
            - identifier
  parameters:
    UserIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
      example: "user123"
paths:
  /users/{id}:
    get:
      summary: Récupère un utilisateur par ID
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        '200':
          description: Utilisateur trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
  /users:
    post:
      summary: Crée des utilisateurs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateUserProfile'
      responses:
        '201':
          description: Utilisateurs créés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
  /users/{id}/personalInfo:
    put:
      summary: Met à jour les informations personnelles
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalInfo'
      responses:
        '200':
          description: Informations mises à jour
  /users/{id}/address:
    put:
      summary: Met à jour l'adresse
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Adresse mise à jour
  /users/{id}/preferences:
    put:
      summary: Met à jour les préférences
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Preferences'
      responses:
        '200':
          description: Préférences mises à jour